In [1]:
import os
os.chdir('..')

In [116]:
import numpy as np
import netCDF4 as nc

In [117]:
X = nc.Dataset('solar/data/kaggle_solar/train/dswrf_sfc_latlon_subset_19940101_20071231.nc','r+').variables.values()

In [135]:
np.array(X[-1])[1:3,np.array((4,5))[:,np.newaxis,np.newaxis,np.newaxis],np.array((1,2,3))[:,np.newaxis, np.newaxis],[[1,2,1,7],[3,2,1,4]],[[3,4,2,4],[6,4,3,2]]]

array([[[[[  20.,   20.,   20.,   10.],
          [  30.,   20.,   20.,   10.]],

         [[ 210.,  210.,  210.,  170.],
          [ 210.,  210.,  210.,  190.]],

         [[ 600.,  590.,  610.,  490.],
          [ 550.,  590.,  600.,  570.]]],


        [[[  20.,   20.,   20.,    0.],
          [  30.,   20.,   20.,   10.]],

         [[ 210.,  210.,  210.,  130.],
          [ 210.,  210.,  210.,  190.]],

         [[ 610.,  590.,  620.,  490.],
          [ 540.,  590.,  610.,  570.]]]],



       [[[[  20.,   20.,   20.,   10.],
          [  30.,   20.,   20.,   10.]],

         [[ 210.,  210.,  210.,  160.],
          [ 210.,  210.,  210.,  190.]],

         [[ 600.,  580.,  610.,  460.],
          [ 550.,  580.,  600.,  550.]]],


        [[[  20.,   20.,   20.,   10.],
          [  30.,   20.,   20.,   10.]],

         [[ 210.,  210.,  210.,  160.],
          [ 210.,  210.,  210.,  190.]],

         [[ 600.,  580.,  610.,  350.],
          [ 550.,  580.,  600.,  550.]]]]], dtype=

In [98]:
count = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[21,22,23],[24,25,26]]])

In [100]:
count[0:3,1:2,1:3]

array([[[ 5,  6]],

       [[14, 15]],

       [[22, 23]]])

In [112]:
count[np.array((0,1,2))[:,np.newaxis],[1,2],[1,2]]

array([[ 5,  9],
       [14, 18],
       [22, 26]])

In [113]:
stlat = 36.5
stlong = 285.1

lats = 2*[int(np.floor(stlat))] + 2*[int(np.ceil(stlat)) + 1]
longs = 2*[int(np.floor(stlong)), int(np.ceil(stlong))+1]

In [114]:
lats

[36, 36, 38, 38]

In [115]:
longs

[285, 287, 285, 287]

In [ ]:
longs.append()