In [1]:
import os
os.chdir('..')

In [2]:
!ls

README.md      bin            log            references     solar
README.md~     data_dump      notebooks      sample.csv     test.csv
README2.md~    images         reference_dump slides


In [8]:
import solar.wrangle.subset
from solar.wrangle.subset import Subset

In [12]:
reload(solar.wrangle.subset)
train_X, train_y, test_X, loc = Subset.subset('solar/data/kaggle_solar/train',
                                                     'solar/data/kaggle_solar/train.csv', 'solar/data/kaggle_solar/',
                                                    'solar/data/kaggle_solar/station_info.csv', {}, {})

KeyboardInterrupt: 

In [33]:
#loc

In [70]:
#train_data

In [71]:
#loc_data

In [11]:
import pandas as pd
loc_data.columns.union(['location'])

Index([u'elev', u'lat', u'location', u'lon'], dtype='object')

In [331]:
reload(subset)
train_X, train_y, test_X, loc = Subset.subset('nothing', 'solar/data/kaggle_solar/train.csv', 'nothing',
                                               'solar/data/kaggle_solar/station_info.csv',
                                               lon=[262,264], lat=[36,37], elev=[200,300],
                                               date=['1996-07-29','1996-08-04'])

RuntimeError: No such file or directory

In [108]:
import netCDF4 as nc

In [110]:
X = nc.Dataset('solar/data/kaggle_solar/train/dswrf_sfc_latlon_subset_19940101_20071231.nc','r+')

In [128]:
import datetime

In [141]:
datetime.datetime.strptime('1996-07-02',"%Y-%m-%d")

datetime.datetime(1996, 7, 2, 0, 0)

In [158]:
import datetime
dates = (X.variables.values()[1][:])
date_range = [datetime.datetime.strptime(str(myDate), "%Y%m%d%H") for myDate in dates]
date_cut1 = 0
date_cut2 = len(date_range)
date_cut3 = date_range.index(datetime.datetime.strptime('1996-07-29',"%Y-%m-%d"))
date_cut4 = date_range.index(datetime.datetime.strptime('1996-08-04',"%Y-%m-%d")) + 1
X.variables.values()[1][date_cut3:date_cut4]


array([1996072900, 1996073000, 1996073100, 1996080100, 1996080200,
       1996080300, 1996080400], dtype=int32)

In [120]:
X.variables.values()[1][1]

1994010200

In [64]:
import pandas as pd
train_y.reset_index(inplace=True)
train_y = train_y.pivot(index='date', columns='location', values='total_solar')

In [80]:
reload(solar.wrangle.wrangle)

<module 'solar.wrangle.wrangle' from 'solar/wrangle/wrangle.py'>

In [641]:
reload(solar.wrangle.wrangle)
from solar.wrangle.wrangle import SolarData
train_X, train_y, test_X = SolarData.load(gefs_train='solar/data/kaggle_solar/train/',
                 gefs_test='solar/data/kaggle_solar/test/',
                 meso_dir='solar/data/kaggle_solar/',
                 files_to_use=['dswrf_sfc'],
                 trainX_dir='solar/data/kaggle_solar/train/',
                 testX_dir='solar/data/kaggle_solar/test/',
                 trainy_file = 'solar/data/kaggle_solar/train.csv',
                 loc_file = 'solar/data/kaggle_solar/station_info.csv')


KeyboardInterrupt: 

In [86]:
train_y

location        ACME      ADAX      ALTU      APAC      ARNE      BEAV  \
date                                                                     
1994-01-01  12384900  11930700  12116700  12301200  10706100  10116900   
1994-01-02  11908500   9778500  10862700  11666400   8062500   9262800   
1994-01-03  12470700   9771900  12627300  12782700  11618400  10789800   
1994-01-04  12725400   6466800  13065300  12817500  12134400  11816700   
1994-01-05  10894800  11545200   8060400  10379400   6918600   9936300   
1994-01-06   6639000   6817200   8157900   7673100   3500400   2245200   
1994-01-07  13244700  12418800  12369900  12873000  12181800   9877800   
1994-01-08  12927900  12375600  12634500  13066500  11608800  11545200   
1994-01-09  12600300  11601000  12156000  12464700  10866000  11295300   
1994-01-10   6406500   3935700  12321900   8164800  11328600  10785000   
1994-01-11  12743400   7137000  12966300  12774600  12005100  11424900   
1994-01-12  10453500   7371000  12855300  11448000  11493000  11794200   
1994-01-13  12985200  12510600  13198500  12726900  12289200  12149100   
1994-01-14  13080000  12552000  13446600  13026600  12393000  12227700   
1994-01-15  11826300  11997300  11313300  11793300  10750200  10290600   
1994-01-16   1974000   1339800   3120600   1058700   7187100   9792900   
1994-01-17  13541700  13021200  13757100  13432800  12486600  11738100   
1994-01-18  13673700  13042200  13881000  13586100  13158300  12724200   
1994-01-19   6796800   8217000  13563300   7861800  13200900  13184700   
1994-01-20   5658900   4757700   1976100   4926000   3088800  10210500   
1994-01-21   7073400  10822800   4021800   6464100   4468500  11169300   
1994-01-22   3354000   2764800   2997900   2726100   8875800  12647400   
1994-01-23   2579700   2339100   6508500   5418600  12936900  12553500   
1994-01-24   2387700   2096700   6390000   3164700   9348300   7642200   
1994-01-25   8390700   8621700  11639100  11404200  11722200  13093500   
1994-01-26   7326600   8104500  10221900   8622300  12958500   7973100   
1994-01-27  10743900   8913000  13336500  11616000  12311700   9855300   
1994-01-28  12812100  13680900  12890700  13834800  13994700  13548000   
1994-01-29   9065100   5018100  10373700  10304100  13456800  13098600   
1994-01-30   3954900   7685700   3863100   4220700   5629200   2520000   
...              ...       ...       ...       ...       ...       ...   
2007-12-02  12177000  11132400  12620100  11796600  11907000  12604500   
2007-12-03  13453800  12737700  12828300  12809700  12264300  12439200   
2007-12-04  12525900  10054800  12328200  12057900  12027900  11833500   
2007-12-05  10543500   8691900  12200100  11790300   9699300  10742100   
2007-12-06   6214500   5707500   6339900   6242400   7813800   8302800   
2007-12-07   8417400   6139800   6981000   6928200   2229600   1899600   
2007-12-08   1683900   1832700   2153700   1853400   2145600   1705200   
2007-12-09   1512300   1394400   1685700   1443900   3815100   5288700   
2007-12-10   1729500   1530600   1451400   1747500   1628400   3313200   
2007-12-11   1512600    819600   1236900   1648800   2398800   2607600   
2007-12-12   2126100   1477500   5262600   2496900   6317400   8295600   
2007-12-13   3476400   3016200   8252400   3503700  11037600  11493600   
2007-12-14   1262700   1544700    921000   1227000   1224300   1073100   
2007-12-15   3074400   1500600   6650400   3486300   7247400   9481800   
2007-12-16  12523800  12006300  12210300  12167100  11643000  12363300   
2007-12-17  12089700  11742900  12130200  11095800  10793100  11952600   
2007-12-18  12300600  11602500  12087900  11866200  11452500  11811900   
2007-12-19  12206100  11478000  12020400  11741100  10871400  11946600   
2007-12-20  12275700  11530800  12134400  11865600  11614800  11707500   
2007-12-21   9737700   9611100   8948400   8915100  10750800   8196000   
2007-12-22   1958400   2235300   2364900   2108700   5511000   8464800   
2007

In [105]:
reload(solar.wrangle.wrangle)
reload(solar.explore.dfsolar)
from solar.explore.dfsolar import SolarDF
trainy, loc = SolarDF.create_df('solar/data/kaggle_solar/train/',
               'solar/data/kaggle_solar/train.csv',
               'solar/data/kaggle_solar/test/',
               'solar/data/kaggle_solar/station_info.csv')


In [107]:
loc

lat        lon  elev
location                           
ACME      34.80833  261.97675   397
ADAX      34.79851  263.33091   295
ALTU      34.58722  260.66192   416
APAC      34.91418  261.70784   440
ARNE      36.07204  260.09692   719
BEAV      36.80253  259.46988   758
BESS      35.40185  260.94153   511
BIXB      35.96305  264.13379   184
BLAC      36.75443  262.74548   304
BOIS      36.69256  257.50287  1267
BOWL      35.17156  263.36879   281
BREC      36.41201  262.30606   352
BRIS      35.78050  263.64596   239
BUFF      36.83129  260.35899   559
BURB      36.63459  263.18954   301
BURN      33.89376  262.73082   228
BUTL      35.59150  260.72941   520
BYAR      34.84970  262.99670   345
CAMA      36.02866  260.65348   589
CENT      34.60896  263.66691   208
CHAN      35.65282  263.19593   291
CHER      36.74813  261.63726   362
CHEY      35.54615  260.27210   694
CHIC      35.03236  262.08554   328
CLAY      34.65657  264.67404   186
CLOU      34.22321  264.75130   221
COOK      35.68001  265.15104   299
COPA      36.90987  264.11447   250
DURA      33.92075  263.67973   197
ELRE      35.54848  261.96346   419
...            ...        ...   ...
PERK      35.99865  262.95169   292
PRYO      36.36914  264.72862   201
PUTN      35.89904  261.03962   589
REDR      36.35590  262.84694   293
RETR      35.12275  260.63999   538
RING      34.19365  262.41188   283
SALL      35.43815  265.20195   157
SEIL      36.19033  260.95970   545
SHAW      35.36492  263.05178   328
SKIA      36.41530  263.96294   282
SLAP      36.59749  259.73808   774
SPEN      35.54208  262.65854   373
STIG      35.26527  264.81884   173
STIL      36.12093  262.90473   272
STUA      34.87642  263.93018   256
SULP      34.56610  263.04952   320
TAHL      35.97235  265.01329   290
TALI      34.71070  264.98848   204
TIPT      34.43972  260.86245   387
TISH      34.33262  263.32105   268
VINI      36.77536  264.77906   236
WASH      34.98224  262.47891   345
WATO      35.84185  261.47385   517
WAUR      34.16775  262.01185   283
WEAT      35.50830  261.22491   538
WEST      36.01100  265.35504   348
WILB      34.90092  264.65195   199
WIST      34.98426  265.31222   143
WOOD      36.42329  260.58318   625
WYNO      36.51806  263.65778   269

[98 rows x 3 columns]

In [637]:
reload(subset)
from solar.wrangle.subset import Subset
X = Subset.cutX('solar/data/kaggle_solar/train/dswrf_sfc_latlon_subset_19940101_20071231.nc', ['2005-07-01', '2005-07-11'])
X.shape

(11, 7920)

In [638]:
X

array([[   0.,    0.,    0., ...,  740.,  732.,  722.],
       [   0.,    0.,    0., ...,  732.,  731.,  729.],
       [   0.,    0.,    0., ...,  714.,  713.,  711.],
       ..., 
       [   0.,    0.,    0., ...,  716.,  708.,  704.],
       [   0.,    0.,    0., ...,  717.,  717.,  710.],
       [   0.,    0.,    0., ...,  410.,  238.,  145.]], dtype=float32)

In [636]:
reload(subset)
from solar.wrangle.subset import Subset
train_dates = ['2005-07-29','2005-08-02']
test_dates = ['2008-12-29', '2009-07-05']
var = ['dswrf_sfc', 'uswrf_sfc', 'spfh_2m']
#var = ['dswrf_sfc']
X_train,y_train, X_test, loc = Subset.subset('solar/data/kaggle_solar/train/', 'solar/data/kaggle_solar/train.csv', 
                                'solar/data/kaggle_solar/test', 'solar/data/kaggle_solar/station_info.csv',
                                var=var, train_dates=train_dates, test_dates=test_dates)

TypeError: subset() got an unexpected keyword argument 'var'

In [222]:
X_train.shape

(5, 200)

In [216]:
X_test.shape

(189, 600)

In [210]:
X_train[:,0:5]

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [225]:
X = nc.Dataset('solar/data/kaggle_solar/gefs_elevations.nc','r+').variables.values()

In [233]:
X[0][:,:]

array([[ 1420.69921875,  1346.98999023,  1323.47143555,   878.61212158,
          801.24279785,   772.99139404,   680.35266113,   468.46411133,
          336.59414673,   120.04213715,    93.48233032,    80.08352661,
           71.31672668,    67.95700073,    10.96530247,    84.81010437],
       [ 1474.9440918 ,  1352.80102539,   898.38110352,   931.03393555,
          826.75177002,   727.69311523,   609.39532471,   482.50411987,
          337.76724243,   183.77027893,   102.97228241,   126.72296143,
           79.13974762,    45.89136505,    33.39725113,    45.70795822],
       [ 1580.38391113,  1424.21606445,  1176.40063477,  1125.14440918,
          948.33728027,   705.66314697,   500.02255249,   368.81665039,
          315.66757202,   163.46469116,   154.10418701,   121.90529633,
           75.23279572,    77.095047  ,    30.76555252,    26.19908905],
       [ 1893.47827148,  1518.9107666 ,  1275.55419922,  1200.21240234,
         1043.76013184,   853.44262695,   502.66729736,   344

In [234]:
X = nc.Dataset('solar/data/kaggle_solar/train/dswrf_sfc_latlon_subset_19940101_20071231.nc','r+')

In [235]:
X = X.variables.values()[-1]

The following two lines would show how I could add an aggregation to my data. I may want to add an aggregation or collapse a dimension into one or more aggregations. This should be done separately from subsetting, though. Still, this should come before creating the DataFrame because collapsing a dimension may be useful to do before too much memory is eaten.

In [240]:
print X.shape
print np.mean(X,axis=1).shape

(5113, 11, 5, 9, 16)
(5113, 5, 9, 16)


In [243]:
np.append(X,np.mean(X,axis=1)[:,None,:,:,:],axis=1).shape

(5113, 12, 5, 9, 16)

    To just index on a list of given models, we can just pass the list as an index. There are 11 models (0 - 10).

In [245]:
models=[0,3,5]
X[:,models,:,:,:].shape

(5113, 3, 5, 9, 16)

In [ ]:
X[:,np.arange(11),:,:,:].shape

Now add the lat and lon cuts

In [273]:
np.arange('2005-02', '2005-03', dtype='datetime64[D]')

array(['2005-02-01', '2005-02-02', '2005-02-03', '2005-02-04',
       '2005-02-05', '2005-02-06', '2005-02-07', '2005-02-08',
       '2005-02-09', '2005-02-10', '2005-02-11', '2005-02-12',
       '2005-02-13', '2005-02-14', '2005-02-15', '2005-02-16',
       '2005-02-17', '2005-02-18', '2005-02-19', '2005-02-20',
       '2005-02-21', '2005-02-22', '2005-02-23', '2005-02-24',
       '2005-02-25', '2005-02-26', '2005-02-27', '2005-02-28'], dtype='datetime64[D]')

OK, now try with date and model cuts

In [335]:
reload(subset)
from solar.wrangle.subset import Subset
train_dates = ['2005-07-29','2005-08-02']
#test_dates = ['2008-12-29', '2009-07-05']
models = [0,5,10]
times = [18,21,24]
lats=range(32,36)
longs=range(260,265)
X = Subset.cutX('solar/data/kaggle_solar/train/dswrf_sfc_latlon_subset_19940101_20071231.nc', train_dates,
                models=models,times=times, lats=lats, longs=longs)
X.shape

4227
4232
Begin date: 4227
End date: 4232
Models: 0, 5, 10
[1 2 3]
[1 2 3 4]
[ 6  7  8  9 10]
Subset complete


(5, 180)

In [344]:
reload(subset)
from solar.wrangle.subset import Subset
train_dates = ['2005-07-29','2005-08-02']
test_dates = ['2008-12-29', '2009-01-05']
var = ['dswrf_sfc', 'uswrf_sfc', 'spfh_2m']
#var = ['dswrf_sfc']
models = [0,5,10]
times = [18, 21, 24]
lats = range(32,36)
longs = range(260,265)
X_train,y_train, X_test, loc = Subset.subset('solar/data/kaggle_solar/train/', 'solar/data/kaggle_solar/train.csv', 
                                'solar/data/kaggle_solar/test', 'solar/data/kaggle_solar/station_info.csv',
                                var=var, train_dates=train_dates, test_dates=test_dates, models=models, times=times,
                                lats=lats, longs=longs)

In [349]:
X_test.shape

(8, 9, 4, 4, 5)

In [274]:
X = nc.Dataset('solar/data/kaggle_solar/train/dswrf_sfc_latlon_subset_19940101_20071231.nc','r+').variables.values()

In [294]:
X[2]

<type 'netCDF4._netCDF4.Variable'>
float32 lat(lat)
    long_name: Latitude
    standard_name: latitude
    units: degrees_north
    actual_range: [ 31.  39.]
    axis: Y
unlimited dimensions: 
current shape = (9,)
filling on, default _FillValue of 9.96920996839e+36 used

In [295]:
X[3]

<type 'netCDF4._netCDF4.Variable'>
float32 lon(lon)
    long_name: Longitude
    standard_name: longitude
    units: degrees_east
    actual_range: [ 254.  269.]
    axis: X
unlimited dimensions: 
current shape = (16,)
filling on, default _FillValue of 9.96920996839e+36 used

In [300]:
times = np.arange(15,25,3)

In [303]:
(times - 15)//3

array([0, 1, 2, 3])

Now that the subsetting is working, use wrangle to get it into the form appropriate for the work-- either learn or explore

In [631]:
reload(solar.wrangle.wrangle)
reload(solar.wrangle.subset)
from solar.wrangle.wrangle import SolarData
from solar.wrangle.subset import Subset
train_dates = ['2005-07-29','2005-08-02']
test_dates = ['2008-12-29', '2009-01-05']
#var = ['dswrf_sfc', 'uswrf_sfc', 'spfh_2m', 'ulwrf_tatm']
var = ['dswrf_sfc']
models = [0]
times = [12]
lats = range(35,37)
longs = range(260,262)
X_train,y_train, X_test = SolarData.load('solar/data/kaggle_solar/train/', 'solar/data/kaggle_solar/train.csv', 
                                'solar/data/kaggle_solar/test', 'solar/data/kaggle_solar/station_info.csv',
                                var=var, lats=lats, longs=longs, test_dates=test_dates, train_dates=train_dates,
                                models=models, times=times)

Training data shape (5, 4) (5, 29)


In [630]:
X_test

variable   dswrf_sfc            
model              0            
time              12            
lat               35      36    
lon              260 261 260 261
date                            
2008-01-01         0   0   0   0
2008-01-02         0   0   0   0
2008-01-03         0   0   0   0
2008-01-04         0   0   0   0
2008-01-05         0   0   0   0
2008-01-06         0   0   0   0
2008-01-07         0   0   0   0
2008-01-08         0   0   0   0
2008-01-09         0   0   0   0
2008-01-10         0   0   0   0
2008-01-11         0   0   0   0
2008-01-12         0   0   0   0
2008-01-13         0   0   0   0
2008-01-14         0   0   0   0
2008-01-15         0   0   0   0
2008-01-16         0   0   0   0
2008-01-17         0   0   0   0
2008-01-18         0   0   0   0
2008-01-19         0   0   0   0
2008-01-20         0   0   0   0
2008-01-21         0   0   0   0
2008-01-22         0   0   0   0
2008-01-23         0   0   0   0
2008-01-24         0   0   0   0
2008-01-25         0   0   0   0
2008-01-26         0   0   0   0
2008-01-27         0   0   0   0
2008-01-28         0   0   0   0
2008-01-29         0   0   0   0
2008-01-30         0   0   0   0
...              ...  ..  ..  ..
2009-12-02         0   0   0   0
2009-12-03         0   0   0   0
2009-12-04         0   0   0   0
2009-12-05         0   0   0   0
2009-12-06         0   0   0   0
2009-12-07         0   0   0   0
2009-12-08         0   0   0   0
2009-12-09         0   0   0   0
2009-12-10         0   0   0   0
2009-12-11         0   0   0   0
2009-12-12         0   0   0   0
2009-12-13         0   0   0   0
2009-12-14         0   0   0   0
2009-12-15         0   0   0   0
2009-12-16         0   0   0   0
2009-12-17         0   0   0   0
2009-12-18         0   0   0   0
2009-12-19         0   0   0   0
2009-12-20         0   0   0   0
2009-12-21         0   0   0   0
2009-12-22         0   0   0   0
2009-12-23         0   0   0   0
2009-12-24         0   0   0   0
2009-12-25         0   0   0   0
2009-12-26         0   0   0   0
2009-12-27         0   0   0   0
2009-12-28         0   0   0   0
2009-12-29         0   0   0   0
2009-12-30         0   0   0   0
2009-12-31         0   0   0   0

[731 rows x 4 columns]

In [576]:
X_train.reset_index().set_index(['date','model','time','lat','lon']).unstack(['model','time','lat','lon']).drop('level_0',axis=1)

variable     dswrf_sfc                                                  \
model               0                                                    
time                15                                                   
lat                 34                                              35   
lon                260         261         262         263         260   
date                                                                     
2005-07-29    0.000000    0.000000    0.000000    0.000000    0.000000   
2005-07-30    0.000000    0.000000    0.000000    0.000000    0.000000   
2005-07-31    0.007220    0.007430    0.008590    0.008750    0.005820   
2005-08-01  302.983765  306.983765  309.983765  308.983765  295.983765   
2005-08-02    0.000000    0.000000    0.000000    0.000000    0.000000   

variable                                                                \
model                                                                    
time                                                                     
lat                                                     36               
lon                261         262         263         260         261   
date                                                                     
2005-07-29    0.000000    0.000000    0.000000    0.000000    0.000000   
2005-07-30    0.000000    0.000000    0.000000    0.000000    0.000000   
2005-07-31    0.006320    0.007010    0.006600    0.005100    0.005750   
2005-08-01  294.983765  291.983765  289.983765  293.983765  292.983765   
2005-08-02    0.000000    0.000000    0.000000    0.000000    0.000000   

variable       ...       uswrf_sfc                                      \
model          ...              10                                       
time           ...              21                                       
lat            ...              34                      35               
lon            ...             262         263         260         261   
date           ...                                                       
2005-07-29     ...      110.000000  111.000000  122.000000  115.000000   
2005-07-30     ...        0.011610    0.012800    0.012400    0.010770   
2005-07-31     ...      300.112732  299.112732  299.112732  296.112732   
2005-08-01     ...      556.000000  571.000000  533.000000  546.000000   
2005-08-02     ...      112.000000  115.000000  123.000000  117.000000   

variable                                                                \
model                                                                    
time                                                                     
lat                                         36                           
lon                262         263         260         261         262   
date                                                                     
2005-07-29  111.000000  112.000000  118.000000  114.000000  112.000000   
2005-07-30    0.011290    0.013070    0.012220    0.010470    0.009910   
2005-07-31  294.112732  294.112732  293.112732  291.112732  291.112732   
2005-08-01  554.000000  567.000000  535.000000  548.000000  554.000000   
2005-08-02  111.000000  114.000000  119.000000  115.000000  111.000000   

variable                
model                   
time                    
lat                     
lon                263  
date                    
2005-07-29  112.000000  
2005-07-30    0.012940  
2005-07-31  290.112732  
2005-08-01  564.000000  
2005-08-02  113.000000  

[5 rows x 192 columns]

In [561]:
%matplotlib inline
import matplotlib.pyplot as plt
ulwrf = X_train[(X_train['time'] == 21) & (X_train['model'] == 10)][['date','ulwrf_tatm']]

In [531]:
Xrev.groupby('lon')

KeyError: 'lon'

In [422]:
from datetime import datetime as dt
X_train.set_index(np.arange(train_dates[0],np.datetime64(train_dates[1])+1,dtype='datetime64'))

AttributeError: 'numpy.ndarray' object has no attribute 'set_index'

In [374]:
np.product(X_train.shape[1:])

48

I think the key to shaping this appropriately can be found in the call below (which won't work on this notebook)

In [361]:
one_loc_one_day.set_index(['date','time','model','latitude','longitude',]).unstack(['time','model','latitude','longitude'])

NameError: name 'one_loc_one_day' is not defined

In [642]:
import solar.wrangle.subset


In [729]:
reload(solar.wrangle.subset)
from solar.wrangle.subset import Subset
train_file = 'solar/data/kaggle_solar/train.csv'
loc_file = 'solar/data/kaggle_solar/station_info.csv'

train_dates = ['2005-07-29','2005-08-29']
#test_dates = ['2008-12-29', '2009-01-29']
#var = ['dswrf_sfc', 'uswrf_sfc', 'spfh_2m', 'ulwrf_tatm']
#var = ['dswrf_sfc']
#models = [0]
#times = [18]
lats = range(35,38)
longs = range(259,270)
trainy, locy = Subset.create_ydata(train_file, loc_file, train_dates=train_dates, lats=lats,
                    longs=longs)


In [734]:
trainy

location  total_solar
date                            
1994-01-01     ACME     12384900
1994-01-02     ACME     11908500
1994-01-03     ACME     12470700
1994-01-04     ACME     12725400
1994-01-05     ACME     10894800
1994-01-06     ACME      6639000
1994-01-07     ACME     13244700
1994-01-08     ACME     12927900
1994-01-09     ACME     12600300
1994-01-10     ACME      6406500
1994-01-11     ACME     12743400
1994-01-12     ACME     10453500
1994-01-13     ACME     12985200
1994-01-14     ACME     13080000
1994-01-15     ACME     11826300
1994-01-16     ACME      1974000
1994-01-17     ACME     13541700
1994-01-18     ACME     13673700
1994-01-19     ACME      6796800
1994-01-20     ACME      5658900
1994-01-21     ACME      7073400
1994-01-22     ACME      3354000
1994-01-23     ACME      2579700
1994-01-24     ACME      2387700
1994-01-25     ACME      8390700
1994-01-26     ACME      7326600
1994-01-27     ACME     10743900
1994-01-28     ACME     12812100
1994-01-29     ACME      9065100
1994-01-30     ACME      3954900
...             ...          ...
2007-12-02     WYNO      7718700
2007-12-03     WYNO     12414000
2007-12-04     WYNO     10495500
2007-12-05     WYNO     11064900
2007-12-06     WYNO      3435000
2007-12-07     WYNO      1757400
2007-12-08     WYNO      1762500
2007-12-09     WYNO      1480200
2007-12-10     WYNO      2024400
2007-12-11     WYNO      1549800
2007-12-12     WYNO      1726800
2007-12-13     WYNO      3342000
2007-12-14     WYNO      1885800
2007-12-15     WYNO      4438800
2007-12-16     WYNO     11652000
2007-12-17     WYNO     10910400
2007-12-18     WYNO     10991700
2007-12-19     WYNO      9920100
2007-12-20     WYNO     11154000
2007-12-21     WYNO      9162900
2007-12-22     WYNO       902400
2007-12-23     WYNO     11434800
2007-12-24     WYNO     11464800
2007-12-25     WYNO     11517300
2007-12-26     WYNO      2382300
2007-12-27     WYNO      1100400
2007-12-28     WYNO      6705900
2007-12-29     WYNO     10586400
2007-12-30     WYNO     11281800
2007-12-31     WYNO     11211300

[501074 rows x 2 columns]

In [749]:
import datetime
my_day = pd.datetime(2005,7,29)
trainy.loc[my_day]

location  total_solar
date                            
2005-07-29     ACME     28302900
2005-07-29     ADAX     28374300
2005-07-29     ALTU     29089800
2005-07-29     APAC     28795800
2005-07-29     ARNE     29379600
2005-07-29     BEAV     29221200
2005-07-29     BESS     29013300
2005-07-29     BIXB     28278000
2005-07-29     BLAC     28506300
2005-07-29     BOIS     30122100
2005-07-29     BOWL     27890700
2005-07-29     BREC     28125000
2005-07-29     BRIS     28349400
2005-07-29     BUFF     28953900
2005-07-29     BURB     28231800
2005-07-29     BURN     28574700
2005-07-29     BUTL     28847400
2005-07-29     BYAR     28510500
2005-07-29     CAMA     29035800
2005-07-29     CENT     29591700
2005-07-29     CHAN     28728900
2005-07-29     CHER     28322400
2005-07-29     CHEY     29353200
2005-07-29     CHIC     28526400
2005-07-29     CLAY     29033400
2005-07-29     CLOU     25347900
2005-07-29     COOK     27720300
2005-07-29     COPA     28366800
2005-07-29     DURA     28915500
2005-07-29     ELRE     27636300
...             ...          ...
2005-07-29     PERK     28868700
2005-07-29     PRYO     28378500
2005-07-29     PUTN     29023500
2005-07-29     REDR     28584900
2005-07-29     RETR     29106600
2005-07-29     RING     29673600
2005-07-29     SALL     26485500
2005-07-29     SEIL     29026200
2005-07-29     SHAW     28946700
2005-07-29     SKIA     28616100
2005-07-29     SLAP     29814600
2005-07-29     SPEN     28958400
2005-07-29     STIG     28024800
2005-07-29     STIL     28285800
2005-07-29     STUA     28854300
2005-07-29     SULP     28752900
2005-07-29     TAHL     28624500
2005-07-29     TALI     25045500
2005-07-29     TIPT     27621900
2005-07-29     TISH     28919700
2005-07-29     VINI     28774500
2005-07-29     WASH     28765500
2005-07-29     WATO     28487400
2005-07-29     WAUR     28987800
2005-07-29     WEAT     28833600
2005-07-29     WEST     25235400
2005-07-29     WILB     25432800
2005-07-29     WIST     22865100
2005-07-29     WOOD     29394300
2005-07-29     WYNO     28616100

[98 rows x 2 columns]

In [801]:
reload(solar.wrangle.subset)
from solar.wrangle.subset import Subset
train_file = 'solar/data/kaggle_solar/train.csv'
loc_file = 'solar/data/kaggle_solar/station_info.csv'

train_dates = ['2005-07-29','2005-08-29']
#test_dates = ['2008-12-29', '2009-01-29']
#var = ['dswrf_sfc', 'uswrf_sfc', 'spfh_2m', 'ulwrf_tatm']
#var = ['dswrf_sfc']
#models = [0]
#times = [18]
lats = [35,38]
longs = [259,270]
train2, loc2 = Subset.reduced_training(trainy, locy, train_dates, [], lats, longs, [])

In [803]:
train2

location  total_solar
date                            
2005-07-29     ARNE     29379600
2005-07-30     ARNE     27992700
2005-07-31     ARNE     27732300
2005-08-01     ARNE     27945300
2005-08-02     ARNE     27709800
2005-08-03     ARNE     25301400
2005-08-04     ARNE     12496800
2005-08-05     ARNE     18632700
2005-08-06     ARNE     18635100
2005-08-07     ARNE     22751700
2005-08-08     ARNE     25019400
2005-08-09     ARNE     26935200
2005-08-10     ARNE     26415900
2005-08-11     ARNE     25321200
2005-08-12     ARNE     19484400
2005-08-13     ARNE      9786900
2005-08-14     ARNE      4866300
2005-08-15     ARNE      7564200
2005-08-16     ARNE     13585500
2005-08-17     ARNE     23143200
2005-08-18     ARNE     22884600
2005-08-19     ARNE     24727200
2005-08-20     ARNE     21304500
2005-08-21     ARNE     11318700
2005-08-22     ARNE     21919500
2005-08-23     ARNE     22713600
2005-08-24     ARNE     16776900
2005-08-25     ARNE     23188200
2005-08-26     ARNE     24423000
2005-08-27     ARNE     17264400
...             ...          ...
2005-07-31     WYNO     27518400
2005-08-01     WYNO     26819400
2005-08-02     WYNO     26225400
2005-08-03     WYNO     24142500
2005-08-04     WYNO     13080300
2005-08-05     WYNO     23871000
2005-08-06     WYNO     21292200
2005-08-07     WYNO     24240900
2005-08-08     WYNO     24124800
2005-08-09     WYNO     25106700
2005-08-10     WYNO     23270400
2005-08-11     WYNO     21712200
2005-08-12     WYNO     20889600
2005-08-13     WYNO     12311700
2005-08-14     WYNO      5597400
2005-08-15     WYNO     11963700
2005-08-16     WYNO     15162000
2005-08-17     WYNO     20068800
2005-08-18     WYNO     24908400
2005-08-19     WYNO     25224900
2005-08-20     WYNO     13243500
2005-08-21     WYNO     13468800
2005-08-22     WYNO     14201700
2005-08-23     WYNO     21830100
2005-08-24     WYNO     23189400
2005-08-25     WYNO     23467800
2005-08-26     WYNO     24069900
2005-08-27     WYNO     21114600
2005-08-28     WYNO     18979200
2005-08-29     WYNO     24023700

[1952 rows x 2 columns]

In [805]:
import datetime
my_day = pd.datetime(2005,7,29)
train2[train2['location'] == 'BEAV'].notnull().describe()

location total_solar
count       32          32
mean         1           1
std          0           0
min       True        True
25%          1           1
50%          1           1
75%          1           1
max       True        True

In [796]:
reload(solar.wrangle.subset)
from solar.wrangle.subset import Subset
train_file = 'solar/data/kaggle_solar/train.csv'
loc_file = 'solar/data/kaggle_solar/station_info.csv'

train_dates = ['2005-07-29','2005-08-29']
#test_dates = ['2008-12-29', '2009-01-29']
#var = ['dswrf_sfc', 'uswrf_sfc', 'spfh_2m', 'ulwrf_tatm']
#var = ['dswrf_sfc']
#models = [0]
#times = [18]
lats = [35,38]
longs = [259,270]
train3, loc3 = Subset.cut_var(trainy, locy, lats, 'lat', train2.columns, loc2.columns)

In [799]:
#loc3

In [800]:
import datetime
my_day = pd.datetime(2005,7,29)
train3.loc[my_day]

location  total_solar
date                            
2005-07-29     ARNE     29379600
2005-07-29     BEAV     29221200
2005-07-29     BESS     29013300
2005-07-29     BIXB     28278000
2005-07-29     BLAC     28506300
2005-07-29     BOIS     30122100
2005-07-29     BOWL     27890700
2005-07-29     BREC     28125000
2005-07-29     BRIS     28349400
2005-07-29     BUFF     28953900
2005-07-29     BURB     28231800
2005-07-29     BUTL     28847400
2005-07-29     CAMA     29035800
2005-07-29     CHAN     28728900
2005-07-29     CHER     28322400
2005-07-29     CHEY     29353200
2005-07-29     CHIC     28526400
2005-07-29     COOK     27720300
2005-07-29     COPA     28366800
2005-07-29     ELRE     27636300
2005-07-29     ERIC     29162100
2005-07-29     EUFA     28458900
2005-07-29     FAIR     28535700
2005-07-29     FORA     28190100
2005-07-29     FREE     28879500
2005-07-29     FTCB     28638300
2005-07-29     GOOD     30098100
2005-07-29     GUTH     28416900
2005-07-29     HASK     28410900
2005-07-29     HINT     28447800
...             ...          ...
2005-07-29     MAYR     29145600
2005-07-29     MEDF     27402000
2005-07-29     MIAM     28367700
2005-07-29     MINC     28316400
2005-07-29     NEWK     28536600
2005-07-29     NOWA     27794100
2005-07-29     OILT     28437000
2005-07-29     OKEM     28340700
2005-07-29     OKMU     28133700
2005-07-29     PAWN     28244100
2005-07-29     PERK     28868700
2005-07-29     PRYO     28378500
2005-07-29     PUTN     29023500
2005-07-29     REDR     28584900
2005-07-29     RETR     29106600
2005-07-29     SALL     26485500
2005-07-29     SEIL     29026200
2005-07-29     SHAW     28946700
2005-07-29     SKIA     28616100
2005-07-29     SLAP     29814600
2005-07-29     SPEN     28958400
2005-07-29     STIG     28024800
2005-07-29     STIL     28285800
2005-07-29     TAHL     28624500
2005-07-29     VINI     28774500
2005-07-29     WATO     28487400
2005-07-29     WEAT     28833600
2005-07-29     WEST     25235400
2005-07-29     WOOD     29394300
2005-07-29     WYNO     28616100

[65 rows x 2 columns]

In [709]:
locy

lat        lon  elev
location                           
ACME      34.80833  261.97675   397
ADAX      34.79851  263.33091   295
ALTU      34.58722  260.66192   416
APAC      34.91418  261.70784   440
ARNE      36.07204  260.09692   719
BEAV      36.80253  259.46988   758
BESS      35.40185  260.94153   511
BIXB      35.96305  264.13379   184
BLAC      36.75443  262.74548   304
BOIS      36.69256  257.50287  1267
BOWL      35.17156  263.36879   281
BREC      36.41201  262.30606   352
BRIS      35.78050  263.64596   239
BUFF      36.83129  260.35899   559
BURB      36.63459  263.18954   301
BURN      33.89376  262.73082   228
BUTL      35.59150  260.72941   520
BYAR      34.84970  262.99670   345
CAMA      36.02866  260.65348   589
CENT      34.60896  263.66691   208
CHAN      35.65282  263.19593   291
CHER      36.74813  261.63726   362
CHEY      35.54615  260.27210   694
CHIC      35.03236  262.08554   328
CLAY      34.65657  264.67404   186
CLOU      34.22321  264.75130   221
COOK      35.68001  265.15104   299
COPA      36.90987  264.11447   250
DURA      33.92075  263.67973   197
ELRE      35.54848  261.96346   419
...            ...        ...   ...
PERK      35.99865  262.95169   292
PRYO      36.36914  264.72862   201
PUTN      35.89904  261.03962   589
REDR      36.35590  262.84694   293
RETR      35.12275  260.63999   538
RING      34.19365  262.41188   283
SALL      35.43815  265.20195   157
SEIL      36.19033  260.95970   545
SHAW      35.36492  263.05178   328
SKIA      36.41530  263.96294   282
SLAP      36.59749  259.73808   774
SPEN      35.54208  262.65854   373
STIG      35.26527  264.81884   173
STIL      36.12093  262.90473   272
STUA      34.87642  263.93018   256
SULP      34.56610  263.04952   320
TAHL      35.97235  265.01329   290
TALI      34.71070  264.98848   204
TIPT      34.43972  260.86245   387
TISH      34.33262  263.32105   268
VINI      36.77536  264.77906   236
WASH      34.98224  262.47891   345
WATO      35.84185  261.47385   517
WAUR      34.16775  262.01185   283
WEAT      35.50830  261.22491   538
WEST      36.01100  265.35504   348
WILB      34.90092  264.65195   199
WIST      34.98426  265.31222   143
WOOD      36.42329  260.58318   625
WYNO      36.51806  263.65778   269

[98 rows x 3 columns]

In [710]:
reload(solar.wrangle.subset)
from solar.wrangle.subset import Subset
trainy_file = 'solar/data/kaggle_solar/train.csv'
loc_file = 'solar/data/kaggle_solar/station_info.csv'
trainX_dir = 'solar/data/kaggle_solar/train/'
testX_dir = 'solar/data/kaggle_solar/test'

train_dates = ['2005-07-29','2005-08-29']
test_dates = ['2008-12-29', '2009-01-01']
#var = ['dswrf_sfc', 'uswrf_sfc', 'spfh_2m', 'ulwrf_tatm']
var = ['dswrf_sfc']
models = [0]
times = [18]
lats = range(35,38)
longs = range(260,268)
X_par = {'train_dates':train_dates, 'test_dates':test_dates, 'var':var, 'models':models, 'times':times, 'lats':lats,
        'longs':longs}
y_par = {'train_dates':train_dates, 'lats':lats, 'longs':longs}

__, trainy, __, __ = Subset.subset(trainX_dir, trainy_file, testX_dir, loc_file, X_par, y_par)


In [807]:
beavs = trainy[(trainy['location'] == 'BEAV')]

In [808]:
beavs.loc[pd.datetime(2005,7,29)]

location           BEAV
total_solar    29221200
Name: 2005-07-29 00:00:00, dtype: object